python -m torch.distributed.launch --nproc_per_node 8 --use_env main.py \
--combine_datasets minedojo --combine_datasets_val minedojo --save_dir=/FrozenBiLM/output/minedojo \
--lr=3e-5 --ds_factor_ff=8 --ds_factor_attn=8 \
--batch_size=96 --batch_size_val=16 --epochs=1000 \
--eval_skip=80 \
--max_feats=16 --features_dim=768 \
--load=/FrozenBiLM/checkpoints/frozenbilm.pth \
--minedojo_text_start=-8 \
--minedojo_text_end=8 \
--minedojo_mask_probs 0 0.15 0.15 \
--minedojo_loss_weights 0 1 1 \
